Enhance CI workflow: add disk space cleanup steps in Build_Push_Images job
Signed-off-by: Eugene Fedorenko <eugene.fedor@gmail.com>

diff --git a/.github/workflows/cicd.yaml b/.github/workflows/cicd.yaml
--- a/.github/workflows/cicd.yaml
+++ b/.github/workflows/cicd.yaml
@@ -24,6 +24,20 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v2
 
+      - name: Free up Disk Space
+        run: |
+          # Remove specific Docker images that are no longer needed
+          docker rmi $(docker images -f "dangling=true" -q) || true
+          
+          # Prune unused Docker objects (images, containers, volumes, and networks)
+          docker system prune -f || true
+
+          # Clean up specific directories known to consume a lot of space
+          sudo rm -rf /path/to/large/directory
+
+          # Show disk space usage
+          df -h
+
       - name: Login to GHCR
         uses: docker/login-action@v1 
         with:
@@ -78,6 +92,20 @@ jobs:
     steps:
       - name: Checkout
         uses: actions/checkout@v2
+
+      - name: Free up Disk Space
+        run: |
+          # Remove specific Docker images that are no longer needed
+          docker rmi $(docker images -f "dangling=true" -q) || true
+          
+          # Prune unused Docker objects (images, containers, volumes, and networks)
+          docker system prune -f || true
+
+          # Clean up specific directories known to consume a lot of space
+          sudo rm -rf /path/to/large/directory
+
+          # Show disk space usage
+          df -h
 
       - name: Start Ephemeral Environment
         run: |
